[package]
name = "kqt-lib"
description = "Rust userspace implementation for kqt"
version = "0.1.0"
edition = "2024"

[features]
route = ["dep:net-route"]

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
ed25519-dalek = { version = "2.2.0", features = ["pkcs8", "rand_core"] }
hex = "0.4.3"
quinn = "0.11.9"
quinn-proto = "*"
rand_core = { version = "0.6.4", features = ["getrandom"] }
tokio = { version = "1.46", features = ["net", "rt-multi-thread", "rt", "macros"] }
tun-rs = { path = "../tun-rs", features = ["async"] }
tracing = "0.1.41"
x509-cert = "0.2.5"
const-oid = { version = "0.9.6", features = ["db"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
cidr = { version = "0.3.1", features = ["serde"] }
ring = "*"
pnet_packet = "0.35.0"
net-route = { version = "0.4.6", optional = true }
tokio-util = "0.7.18"
